### ISSUE TITLE
It is not working!!

### ISSUE THREAD

**Issue by NonsensicalOne** [Sof1dev/gayify#1]
Issue: I tried to gayify one of my images, and it stood like that.

Security Thing: By the way, putting public backend url to your .env file doesnt secure it from being reached through inspect element >> network tab

unrelated: please open source the backend as well

**Comment by Sof1dev** [comment]
Thanks for writing an issue!

The backend url enviroment variable isn't supposed to be private, it's just there so the url isn't hardcoded. I'll also open source the backend

**Comment by NonsensicalOne** [comment]
> Thanks for writing an issue!
> 
> The backend url enviroment variable isn't supposed to be private, it's just there so the url isn't hardcoded. I'll also open source the backend

thank you!

**Comment by Sof1dev** [comment]
Hi! I just fixed the website, the API url was wrong and the fetch wasn't working. Also I made the backend open source [here](https://github.com/Sof1dev/gayify-backend)!

Thanks for writting an issue! I wouldn't have noticed otherwise

**Comment by NonsensicalOne** [comment]
thanks again lol
